apiVersion: v1
kind: Pod
metadata:
  name: kube-rndnet-server
  labels:
    app: kube-rndnet-server
spec:
  containers:
  - name: kube-rndnet-server
    image: rndnet/server
    imagePullPolicy: "Always"
    args: ["--config", "/etc/rndnet/rndnet_server.conf", "--accesslog", "/var/log/rndnet_server.log", "--bind", "0.0.0.0:6000", "--no-ssl", "--no-cleanup"]
    volumeMounts:
    - name: rndnet-server-data-volume
      mountPath: "/etc/rndnet/"
      readOnly: true
    - name: rndnet-server-data-volume
      mountPath: "/root/.pgpass"
      subPath: ".pgpass"
      readOnly: true
    workingDir: /  
    ports:
    - containerPort: 6000
      protocol: TCP
  nodeName: epyc-host004.rndnet.net
  volumes:
  - name: rndnet-server-data-volume
    secret:
     secretName: rndnet-server-data
     items:
     - key: conf
       path: rndnet_server.conf
     - key: pgpass
       path: .pgpass
       mode: 0600
