apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-rndnet-scheduler-deployment
  labels:
    app: kube-rndnet-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-rndnet-scheduler
  template:
    metadata:
      labels:
        app: kube-rndnet-scheduler
    spec:
      serviceAccountName: scheduler-sa
      containers:
      - name: kube-rndnet-scheduler
        image: docker.io/rndnet/k8s-scheduler:uni
        imagePullPolicy: "Always"
        args: ["--server", "https://server2.rndnet.net:5000", "--user", "sched_kube_epyc", "--pgpkey", "/etc/rndnet/secret.key", "--params", "docker_image=rndnet/python-bfj:apps"]
        #args: ["--server", "https://server2.rndnet.net:5000", "--user", "sched_kube_tahiti", "--params", "gpu_vendor=amd", "--pgpkey", "/etc/rndnet/secret.key"] # or default "gpu_vendor=nvidia"
        volumeMounts:
        - name: sched-kube-epyc-key
          mountPath: "/etc/rndnet/"
          readOnly: true
        workingDir: /  
      dnsPolicy: Default
      volumes:
      - name: sched-kube-epyc-key
        secret:
          secretName: sched-kube-epyc-key
          items:
          - key: key
            path: secret.key
