apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manage-jobs
rules:
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs:
      - list
      - create
      - delete

