apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scheduler-manage-jobs
subjects:
  - kind: ServiceAccount
    name: scheduler-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: manage-jobs
  apiGroup: rbac.authorization.k8s.io

