{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rndnet-scheduler.fullname" . | printf "%s-manage-jobs" }}
  labels:
    {{- include "rndnet-scheduler.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs:
      - list
      - create
      - delete
{{- end }}
