{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rndnet-scheduler.fullname" . | printf "%s-list-pods" }}
  labels:
    {{- include "rndnet-scheduler.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - list
{{- end }}
