apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rndnet-scheduler.fullname" . }}
  labels:
    {{- include "rndnet-scheduler.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "rndnet-scheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "rndnet-scheduler.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rndnet-scheduler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.scheduler }}
          {{- if .command   }}
          command: {{ .command }}
          {{- end }}
          args: ["--server", "{{ .server }}", "--user", "{{ .user }}", "--pgpkey", "{{ .pgpkey }}"  {{- if .params   }}, "--params"  {{- range .params }}, "{{ . }}" {{- end }} {{- end }} {{- if .type  }}, "--sched", "{{ .type }}" {{- end }} ]
          {{- end }}
          volumeMounts:
          - name: scheduler-key
            mountPath: "/etc/rndnet/"
            readOnly: true
          workingDir: /
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      dnsPolicy: {{ .Values.dns.policy }}
      volumes:
      - name: scheduler-key
        secret:
          secretName:  {{ include "rndnet-scheduler.fullname" . }}
          items:
          - key: key
            path: secret.key
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
